name: Check Documentation Links 

on: [push,pull_request]



jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
          language: [de, en,es,fi,fr,hu,ja,it]

    env:
        LANG_MSG: "[${{ matrix.language }}]"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: get commit message
        run: |
           COMMITMSG=$(git log --format=%B -n 2)
           echo "${COMMITMSG}"
           echo "commitmsg=""${COMMITMSG}""" >> $GITHUB_ENV

      - name: show commit message
        run : echo $commitmsg

      - name: print language
        run: |
          echo "Language:"
          echo "${LANG_MSG}"
          echo "${{ github.event.head_commit.message }}"
          echo "${commitmsg}"

